"""Added client location coordinate values.

Revision ID: c874cd840791
Revises: 461d9eac3a57
Create Date: 2024-10-27 00:19:01.351055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c874cd840791'
down_revision: Union[str, None] = '461d9eac3a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('lat', sa.Float(), nullable=True, comment='Широта'))
    op.add_column('clients', sa.Column('lon', sa.Float(), nullable=True, comment='Долгота'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'lon')
    op.drop_column('clients', 'lat')
    # ### end Alembic commands ###
